- name: Deploy LAMP Stack and Laravel Application
  hosts: slave
  become: 'yes'
  vars:
    ansible_user: vagrant
    ansible_ssh_pass: vagrant
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Copy bash script to the Slave node
      copy:
        src: ~/Scripts/deploy_lamp.sh
        dest: /tmp/deploy_lamp.sh
        mode: '0755'
      tags:
        - copy_script
    - name: Execute the bash script
      command: bash /tmp/deploy_lamp.sh
      args:
        chdir: /tmp
      tags:
        - execute_script
    - name: Add a daily cron job to check server uptime
      cron:
        name: Check Server Uptime
        minute: 0
        hour: 0
        job: uptime >> /var/log/server_uptime.log
        state: present
      tags:
        - setup_cron_job
  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
      tags:
        - restart_apache